### ISSUE TITLE
[UI] Design Tables to be more modern

### ISSUE THREAD

**Issue by KevinGallaccio** [KevinGallaccio/winii#70]
Here's generated code from ChatGPT that is supposed to mirror Notion tables

CSS:
```CSS

/* General Table Styles */
.table-container {
    width: 100%;
    overflow-x: auto;
}

.table {
    border-collapse: separate;
    border-spacing: 0;
    width: 100%;
    border: 1px solid #e2e8f0;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    font-size: 14px;
    color: #333;
}

.table th,
.table td {
    padding: 12px 15px;
    text-align: left;
}

.table thead th {
    background-color: #f7fafc;
    color: #4a5568;
    font-weight: 600;
    border-bottom: 2px solid #edf2f7;
}

.table tbody tr {
    border-bottom: 1px solid #edf2f7;
    transition: background-color 0.2s ease;
}

.table tbody tr:hover {
    background-color: #f1f5f9;
}

.table tbody tr:last-child {
    border-bottom: none;
}

.table td {
    border-right: 1px solid #edf2f7;
}

.table td:last-child {
    border-right: none;
}

/* Responsive Styles */
@media (max-width: 768px) {
    .table-container {
        margin-bottom: 15px;
        overflow-x: auto;
    }
    
    .table th,
    .table td {
        padding: 10px 12px;
    }
}

```
